/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senai.Projeto.projeto;

import br.com.senai.Projeto.Controller.PessoaController;
import br.com.senai.Projeto.model.Pessoa;

/**
 *
 * @author Gustavo
 */
public class Produtos extends javax.swing.JFrame {

    /**
     * Creates new form Produtos
     */
    public Produtos() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        PainelFundo = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PainelSoftwares = new javax.swing.JPanel();
        LabelSoftware = new javax.swing.JLabel();
        PainelAdiquira = new javax.swing.JPanel();
        BotaoAdiquira = new javax.swing.JButton();
        PainelProdutos = new javax.swing.JPanel();
        BotaoGame = new javax.swing.JButton();
        BotaoMac = new javax.swing.JButton();
        LabelGame = new javax.swing.JLabel();
        LabelMac = new javax.swing.JLabel();
        BotaoTab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BotaoCadastrarProdutos = new javax.swing.JButton();
        PainelOutros = new javax.swing.JPanel();
        LabelManutencao = new javax.swing.JLabel();
        LabelFormatacao = new javax.swing.JLabel();
        Labelacessorios = new javax.swing.JLabel();
        LabelAssistencia = new javax.swing.JLabel();
        LabelInformacoes = new javax.swing.JLabel();
        Labelacesse = new javax.swing.JLabel();
        LabelSite = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        PainelSoftwares.setBackground(new java.awt.Color(51, 255, 255));

        LabelSoftware.setText("Software Disponivel");

        PainelAdiquira.setBackground(new java.awt.Color(153, 153, 153));

        BotaoAdiquira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/1016056.png"))); // NOI18N
        BotaoAdiquira.setText("Versão 1.0");

        javax.swing.GroupLayout PainelAdiquiraLayout = new javax.swing.GroupLayout(PainelAdiquira);
        PainelAdiquira.setLayout(PainelAdiquiraLayout);
        PainelAdiquiraLayout.setHorizontalGroup(
            PainelAdiquiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PainelAdiquiraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoAdiquira)
                .addContainerGap())
        );
        PainelAdiquiraLayout.setVerticalGroup(
            PainelAdiquiraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelAdiquiraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(BotaoAdiquira, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PainelSoftwaresLayout = new javax.swing.GroupLayout(PainelSoftwares);
        PainelSoftwares.setLayout(PainelSoftwaresLayout);
        PainelSoftwaresLayout.setHorizontalGroup(
            PainelSoftwaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSoftwaresLayout.createSequentialGroup()
                .addComponent(LabelSoftware, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PainelAdiquira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 252, Short.MAX_VALUE))
        );
        PainelSoftwaresLayout.setVerticalGroup(
            PainelSoftwaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelSoftwaresLayout.createSequentialGroup()
                .addGroup(PainelSoftwaresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelSoftwaresLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(LabelSoftware))
                    .addGroup(PainelSoftwaresLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(PainelAdiquira, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(254, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Softwares", PainelSoftwares);

        PainelProdutos.setBackground(new java.awt.Color(0, 255, 255));

        BotaoGame.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons1.jpg"))); // NOI18N

        BotaoMac.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons2.jpg"))); // NOI18N

        LabelGame.setText("PlayStation3");

        LabelMac.setText("Mac");

        BotaoTab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons.jpg"))); // NOI18N

        jLabel1.setText("Tablet");

        BotaoCadastrarProdutos.setText("Casdastrar Produtos");
        BotaoCadastrarProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastrarProdutosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PainelProdutosLayout = new javax.swing.GroupLayout(PainelProdutos);
        PainelProdutos.setLayout(PainelProdutosLayout);
        PainelProdutosLayout.setHorizontalGroup(
            PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProdutosLayout.createSequentialGroup()
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addComponent(BotaoGame)
                        .addGap(13, 13, 13)
                        .addComponent(LabelGame, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addComponent(BotaoMac)
                        .addGap(15, 15, 15)
                        .addComponent(LabelMac, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addComponent(BotaoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(BotaoCadastrarProdutos)))
                .addContainerGap())
        );
        PainelProdutosLayout.setVerticalGroup(
            PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelProdutosLayout.createSequentialGroup()
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(BotaoTab, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoGame, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LabelGame)))
                .addGap(10, 10, 10)
                .addGroup(PainelProdutosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BotaoMac, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PainelProdutosLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(LabelMac)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(BotaoCadastrarProdutos)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Produtos de Informatica", PainelProdutos);

        PainelOutros.setBackground(new java.awt.Color(0, 255, 255));

        LabelManutencao.setText("Manutenção De Micro Computadores");

        LabelFormatacao.setText("Formatação ");

        Labelacessorios.setText("acessórios de informatica");

        LabelAssistencia.setText("Assistência técnica");

        LabelInformacoes.setText("Para Mais Informções Ligue: 9624-2508");

        Labelacesse.setText("                       Ou Acesse ");

        LabelSite.setText("              www.proinfo.com.br");

        jLabel2.setText("ProInfo");

        javax.swing.GroupLayout PainelOutrosLayout = new javax.swing.GroupLayout(PainelOutros);
        PainelOutros.setLayout(PainelOutrosLayout);
        PainelOutrosLayout.setHorizontalGroup(
            PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOutrosLayout.createSequentialGroup()
                .addGroup(PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PainelOutrosLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelManutencao, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(LabelAssistencia, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Labelacessorios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                .addComponent(LabelFormatacao, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(PainelOutrosLayout.createSequentialGroup()
                        .addGap(154, 154, 154)
                        .addGroup(PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(LabelInformacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Labelacesse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(LabelSite, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(PainelOutrosLayout.createSequentialGroup()
                        .addGap(223, 223, 223)
                        .addComponent(jLabel2)))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        PainelOutrosLayout.setVerticalGroup(
            PainelOutrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelOutrosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelManutencao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelFormatacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Labelacessorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelAssistencia)
                .addGap(51, 51, 51)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(LabelInformacoes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Labelacesse)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(LabelSite)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Ajuda", PainelOutros);

        javax.swing.GroupLayout PainelFundoLayout = new javax.swing.GroupLayout(PainelFundo);
        PainelFundo.setLayout(PainelFundoLayout);
        PainelFundoLayout.setHorizontalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PainelFundoLayout.setVerticalGroup(
            PainelFundoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PainelFundoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PainelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PainelFundo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastrarProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastrarProdutosActionPerformed
        dispose();
        CadastroProdutos cp = new CadastroProdutos();
        
    }//GEN-LAST:event_BotaoCadastrarProdutosActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoAdiquira;
    private javax.swing.JButton BotaoCadastrarProdutos;
    private javax.swing.JButton BotaoGame;
    private javax.swing.JButton BotaoMac;
    private javax.swing.JButton BotaoTab;
    private javax.swing.JLabel LabelAssistencia;
    private javax.swing.JLabel LabelFormatacao;
    private javax.swing.JLabel LabelGame;
    private javax.swing.JLabel LabelInformacoes;
    private javax.swing.JLabel LabelMac;
    private javax.swing.JLabel LabelManutencao;
    private javax.swing.JLabel LabelSite;
    private javax.swing.JLabel LabelSoftware;
    private javax.swing.JLabel Labelacesse;
    private javax.swing.JLabel Labelacessorios;
    private javax.swing.JPanel PainelAdiquira;
    private javax.swing.JPanel PainelFundo;
    private javax.swing.JPanel PainelOutros;
    private javax.swing.JPanel PainelProdutos;
    private javax.swing.JPanel PainelSoftwares;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
